<figure><pre>
sign(User 0's public key, alpha**r0(mod p), alpha**r1(modp))
          ______                          ______
         / User \                        / User \
        (    0   )--------------------->(    1   )
         \______/                        \______/    


sign(User 1's public key, alpha**r1(mod p), alpha**r0(modp))
          ______                          ______
         / User \                        / User \
        (    0   )<---------------------(    1   )
         \______/                        \______/    
</pre></figure>
