#!/usr/bin/env bash
# build-aux/1e0/html2man - Convert stripped+cleaned HTML into manpages
#
# Copyright (C) 2025  Luke T. Shumaker <lukeshu@lukeshu.com>
# SPDX-License-Identifier: MIT

set -euE -o pipefail

# Usage: ./html2man PAGE_NAME CHAPTER_NUM CHAPTER_NAME <infile.phtml >outfile.man
main() {
	page_name=$1
	chapter_num=$2
	chapter_name=$3

	# head
	echo ".TH ${page_name^^} ${chapter_num^^} \"\" \"\" \"${chapter_name}\""

	# body
	{
		# The main conversion.
		pandoc --from=html --to=man --wrap=preserve
	} | {
		# Fuss with markup to be more old-school flavored.
		sed -E \
		    -e 's/^\.SH\s+(\S.*)/.SH \U\1/' \
		    -e 's/^\.SS\s+(\S.*)/.SS \U\1/' \
		    -e 's/\\f\[I\]/\n.I /g' \
		    -e 's/\\f\[B\]/\n.B /g' \
		    -e 's/\\f\[R\]\s*/\n/g' \
		    -e 's/^\\\s*//'
	} | {
		# Trim trailing newlines.
		printf '%s\n' "$(cat)"
	}
}

main "$@"
